# Generated by Django 5.2.8 on 2025-11-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_for_invoice',
            field=models.BooleanField(default=True),
        ),
    ]
