# Generated by Django 5.2.8 on 2025-11-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_available_for_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hs_code',
            field=models.CharField(blank=True, help_text='Harmonized System Code for international trade', max_length=20, null=True),
        ),
    ]
